alter table public.establishments
  add column if not exists address text,
  add column if not exists owner_phone text,
  add column if not exists owner_phone_type text,
  add column if not exists email text,
  add column if not exists manager_phone text,
  add column if not exists manager_phone_type text,
  add column if not exists manager_address text,
  add column if not exists bpa_responsible text,
  add column if not exists bpa_address text,
  add column if not exists bpa_locality text,
  add column if not exists bpa_phone text,
  add column if not exists bpa_phone_type text,
  add column if not exists bpa_email text,
  add column if not exists main_products text,
  add column if not exists secondary_products text,
  add column if not exists seniority text,
  add column if not exists association text,
  add column if not exists member_number text,
  add column if not exists wholesale_market boolean,
  add column if not exists private_company boolean,
  add column if not exists own_transport boolean,
  add column if not exists packing_shed boolean,
  add column if not exists observations text,
  add column if not exists updated_at timestamptz not null default now();

comment on column public.establishments.bpa_responsible is 'Persona designada para supervisar la implementación de BPA en el establecimiento.';

-- Completa los establecimientos de la demostración. Estos datos son ficticios
-- y deben reemplazarse antes de usar AgroVoz con un productor real.
update public.establishments
set
  name = 'La Esperanza',
  address = 'Camino Rural Km 12',
  owner_phone = '351 555-0100',
  owner_phone_type = 'Celular',
  email = 'establecimiento@ejemplo.com',
  manager_phone = '351 555-0101',
  manager_phone_type = 'Celular',
  manager_address = 'Camino Rural Km 12',
  bpa_responsible = 'Lucía Pereyra',
  bpa_address = 'Ruta 9 Km 748',
  bpa_locality = 'Colonia Caroya',
  bpa_phone = '351 555-0102',
  bpa_phone_type = 'Celular',
  bpa_email = 'bpa@ejemplo.com',
  main_products = 'Tomate, pimiento',
  secondary_products = 'Lechuga',
  seniority = '12 años',
  association = 'Cooperativa regional',
  member_number = '184',
  wholesale_market = true,
  private_company = false,
  own_transport = true,
  packing_shed = true,
  observations = 'Datos demostrativos',
  active = true,
  updated_at = now()
where renspa = '04.001.0.01234/00';

update public.establishments
set
  name = 'El Ombú',
  address = 'Camino a Sinsacate Km 4',
  locality = 'Jesús María',
  province = 'Córdoba',
  owner_phone = '3525 555-0200',
  owner_phone_type = 'Celular',
  email = 'elombu@ejemplo.com',
  manager_phone = '3525 555-0201',
  manager_phone_type = 'Celular',
  manager_address = 'Camino a Sinsacate Km 4',
  bpa_responsible = 'Mariana Gómez',
  bpa_address = 'Calle Córdoba 245',
  bpa_locality = 'Jesús María',
  bpa_phone = '3525 555-0202',
  bpa_phone_type = 'Celular',
  bpa_email = 'bpa.elombu@ejemplo.com',
  main_products = 'Pimiento, tomate',
  secondary_products = 'Zapallito',
  seniority = '8 años',
  association = 'Asociación de Productores del Norte Cordobés',
  member_number = '276',
  wholesale_market = true,
  private_company = true,
  own_transport = false,
  packing_shed = true,
  observations = 'Datos demostrativos',
  active = true,
  updated_at = now()
where renspa = '04.001.0.05678/00';
